### PR TITLE
OPCT-9: introduce the report cmd to automate the review steps

### PR DESCRIPTION
**Pull request by mtulio**
This PR introduces the command `report` to be used on the result review stage (post-submit to Red Hat), applying different filters according to checks on the Baseline results and CI flake tests (using Sippy API as a data source)

This command also dumps the failed filtered tests into text files, extracting the details for each failed test to be used while troubleshooting the post-execution.

The following files are optional files to be used alongside the archive:

- baseline results : reference artifacts execution in the OPCT CI Pipeline to help to review the providers artifact

Example of CLI
```bash
./openshift-provider-cert-linux-amd64 report \
  --baseline ./opct_baseline-ocp_4.11.4-platform_none-aws-202210102258_sonobuoy_7a895e01-3d3e-44cc-a5d3-ac4f2ed678fd.tar.gz \
  202210132151_sonobuoy_6af99324-2dc6-4de4-938c-200b84111481.tar.gz  \
  --save-to ./processed-results
```

There are spikes to understand if we can collect include/collect it on the certification runtime, so we can allow end-users to use this command before submitting their results.

https://issues.redhat.com/browse/OPCT-9
https://issues.redhat.com/browse/OPCT-10

### CODE REVIEW

**Comment by mtulio** [comment]
Example of `report` extracting the data to the directory `./results-provider-processed`:
```
$ $CLI_PATH/openshift-provider-cert-linux-amd64-process0 report 4.12.1-20230131.tar.gz --save-to  ./results-provider-processed
INFO[2023-02-01T01:26:25-03:00] Processing Plugin 05-openshift-cluster-upgrade... 
INFO[2023-02-01T01:26:25-03:00] Ignoring Plugin 05-openshift-cluster-upgrade 
INFO[2023-02-01T01:26:25-03:00] Processing Plugin 10-openshift-kube-conformance... 
INFO[2023-02-01T01:26:25-03:00] Processing Plugin 20-openshift-conformance-validated... 
INFO[2023-02-01T01:26:26-03:00] Processing Plugin 99-openshift-artifacts-collector... 
INFO[2023-02-01T01:26:26-03:00] Ignoring Plugin 99-openshift-artifacts-collector 
WARN[2023-02-01T01:26:27-03:00] Ignoring to populate source 'baseline'. Missing or invalid baseline artifact (-b):  

> OpenShift Provider Certification Summary <

 Kubernetes API Server version		: v1.25.4+a34b9e9
 OpenShift Container Platform version	: 4.12.1
 - Cluster Update Progressing		: False
 - Cluster Target Version		: Cluster version is 4.12.1
						
 OCP Infrastructure:			
 - PlatformType				: None
 - Name					: ci-op-nykh40v7-7280e-bsghd
 - Topology				: HighlyAvailable
 - ControlPlaneTopology			: HighlyAvailable
 - API Server URL			: https://api.ci-op-nykh40v7-7280e.vmc-ci.devcluster.openshift.com:6443
 - API Server URL (internal)		: https://api-int.ci-op-nykh40v7-7280e.vmc-ci.devcluster.openshift.com:6443
						
 Plugins summary by name:		  Status [Total/Passed/Failed/Skipped] (timeout)
 - 10-openshift-kube-conformance	: failed [691/669/22/0] (0)
 - 20-openshift-conformance-validated	: failed [3793/1627/52/2114] (0)
									
 Health summary:			  [A=True/P=True/D=True]	
 - Cluster Operators			: [33/0/0]
 - Node health				: 6/6  (100%)
 - Pods health				: 250/258  (96%)

> Processed Summary <

 Total tests by conformance suites:
 - kubernetes/conformance: 359 
 - openshift/conformance: 3454 

 Result Summary by conformance plugins:
 - 10-openshift-kube-conformance:
   - Status: failed
   - Total: 691
   - Passed: 669
   - Failed: 22
   - Timeout: 0
   - Skipped: 0
   - Failed (without filters) : 22
   - Failed (Filter SuiteOnly): 0
   - Failed (Filter CI Flakes): 0
   - Status After Filters     : pass
 - 20-openshift-conformance-validated:
   - Status: failed
   - Total: 3793
   - Passed: 1627
   - Failed: 52
   - Timeout: 0
   - Skipped: 2114
   - Failed (without filters) : 52
   - Failed (Filter SuiteOnly): 22
   - Failed (Filter CI Flakes): 3
   - Status After Filters     : failed

 Result details by conformance plugins: 


 => 10-openshift-kube-conformance: (0 failures, 0 flakes)

 --> Failed tests to Review (without flakes) - Immediate action:
<empty>

 --> Failed flake tests - Statistic from OpenShift CI
<empty>


 => 20-openshift-conformance-validated: (22 failures, 19 flakes)

 --> Failed tests to Review (without flakes) - Immediate action:
[sig-arch] Managed cluster should set requests but not limits [Suite:openshift/conformance/parallel]
[sig-cli] oc basics can get version information from API [Suite:openshift/conformance/parallel]
[sig-scheduling] SchedulerPriorities [Serial] PodTopologySpread Scoring validates pod should be preferably scheduled to node which makes the matching pods more evenly distributed [Suite:openshift/conformance/serial] [Suite:k8s]

 --> Failed flake tests - Statistic from OpenShift CI
Flakes	Perc		 TestName
1	0.134%		[sig-api-machinery][Feature:APIServer] anonymous browsers should get a 403 from / [Suite:openshift/conformance/parallel]
1	0.134%		[sig-arch] Managed cluster should ensure control plane pods do not run in best-effort QoS [Suite:openshift/conformance/parallel]
748	100.000%	[sig-arch] Managed cluster should ensure platform components have system-* priority class associated [Suite:openshift/conformance/parallel]
--	--		[sig-arch][Late] clients should not use APIs that are removed in upcoming releases [apigroup:config.openshift.io] [Suite:openshift/conformance/parallel]
--	--		[sig-auth][Feature:OAuthServer] OAuth server has the correct token and certificate fallback semantics [apigroup:config.openshift.io][apigroup:user.openshift.io] [Suite:openshift/conformance/parallel]
--	--		[sig-auth][Feature:OAuthServer] well-known endpoint should be reachable [apigroup:config.openshift.io][apigroup:route.openshift.io] [Suite:openshift/conformance/parallel]
--	--		[sig-auth][Feature:OpenShiftAuthorization][Serial] authorization TestAuthorizationResourceAccessReview should succeed [apigroup:authorization.openshift.io] [Suite:openshift/conformance/serial]
--	--		[sig-auth][Feature:UserAPI] users can manipulate groups [apigroup:user.openshift.io][apigroup:authorization.openshift.io][apigroup:project.openshift.io] [Suite:openshift/conformance/parallel]
--	--		[sig-builds][Feature:Builds] oc new-app should succeed with an imagestream [apigroup:build.openshift.io] [Skipped:Disconnected] [Suite:openshift/conformance/parallel]
--	--		[sig-cli] oc builds new-build [apigroup:build.openshift.io] [Skipped:Disconnected] [Suite:openshift/conformance/parallel]
--	--		[sig-cli] oc idle [apigroup:apps.openshift.io][apigroup:route.openshift.io][apigroup:project.openshift.io][apigroup:image.openshift.io] by all [Suite:openshift/conformance/parallel]
--	--		[sig-cli] oc idle [apigroup:apps.openshift.io][apigroup:route.openshift.io][apigroup:project.openshift.io][apigroup:image.openshift.io] by label [Suite:openshift/conformance/parallel]
--	--		[sig-cli] oc idle [apigroup:apps.openshift.io][apigroup:route.openshift.io][apigroup:project.openshift.io][apigroup:image.openshift.io] by name [Suite:openshift/conformance/parallel]
--	--		[sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early][apigroup:config.openshift.io] [Skipped:Disconnected] [Suite:openshift/conformance/parallel]
--	--		[sig-instrumentation][Late] Alerts shouldn't report any unexpected alerts in firing or pending state [apigroup:config.openshift.io] [Suite:openshift/conformance/parallel]
--	--		[sig-instrumentation][Late] OpenShift alerting rules [apigroup:image.openshift.io] should have a runbook_url annotation if the alert is critical [Skipped:Disconnected] [Suite:openshift/conformance/parallel]
--	--		[sig-instrumentation][Late] OpenShift alerting rules [apigroup:image.openshift.io] should have description and summary annotations [Skipped:Disconnected] [Suite:openshift/conformance/parallel]
--	--		[sig-network] Services should be rejected for evicted pods (no endpoints exist) [Suite:openshift/conformance/parallel] [Suite:k8s]
--	--		[sig-network] services when running openshift ipv4 cluster ensures external ip policy is configured correctly on the cluster [apigroup:config.openshift.io] [Serial] [Suite:openshift/conformance/serial]

 Data Saved to directory './results-provider-processed/'

```

**Comment by mtulio** [comment]
@rvanderp3 ptal? this PR is almost ready for review. I need to fix only the walkFiles strategy which is hitting the CI, but overall can be reviewed and I will highlight that part.
/assign @rvanderp3 
/hold

**Review by faermanj — COMMENTED** [review]
looks great to me, can't wait to try the new report command

**Comment by rvanderp3** [comment]
LGTM pending a fix to address issue found in CI

**Comment by mtulio** [comment]
@rvanderp3 CI issues fixed. ptal? Thanks

**Comment by rvanderp3** [comment]
> @rvanderp3 CI issues fixed. ptal? Thanks

Yep, I think they are all resolved.

**Comment by mtulio** [comment]
> > @rvanderp3 CI issues fixed. ptal? Thanks
> 
> Yep, I think they are all resolved.

@rvanderp3 Thanks! If you are fine with the review, would you mind setting the approval labels?

**Pull request merged**
