### PR TITLE
Bump to latest sonobuoy and golang 1.21

### PR DESCRIPTION
**Pull request by jcpowermac**
This PR bumps sonobuoy to 0.57.1 and
switches to golang v1.21

### CODE REVIEW

**Comment by jcpowermac** [comment]
Need to manually test this

**Comment by jcpowermac** [comment]
This should be ready to go

```
Mon, 26 Feb 2024 19:20:23 CST> Global Status: post-processing                                                                                                                      
JOB_NAME                           | STATUS     | RESULTS    | PROGRESS                  | MESSAGE                                                                                 
05-openshift-cluster-upgrade       | complete   |            | 0/0 (0 failures)          | waiting for post-processor...                     
10-openshift-kube-conformance      | complete   |            | 384/390 (1 failures)      | waiting for post-processor...                                                           
20-openshift-conformance-validated | complete   |            | 3870/3879 (102 failures)  | waiting for post-processor...                                                           
99-openshift-artifacts-collector   | complete   |            | 0/0 (0 failures)          | waiting for post-processor...                                                           
INFO[2024-02-26T19:20:23-06:00] Waiting for post-processor...                                                                                                                      
Mon, 26 Feb 2024 19:27:23 CST> Global Status: complete                                                                                                                             
JOB_NAME                           | STATUS     | RESULTS    | PROGRESS                  | MESSAGE                                                                                 
05-openshift-cluster-upgrade       | complete   | passed     | 0/0 (0 failures)          | Total tests processed: 1 (1 pass / 0 failed)   
```

```
➜  vsphere-ipi ../opct-linux-amd64 retrieve
INFO[2024-02-27T06:16:19-06:00] Collecting results...                        
INFO[2024-02-27T06:16:33-06:00] Results saved to /home/jcallen/Development/before-installer-testing/vsphere-ipi/202402262142_sonobuoy_fd9c2eb3-e6ea-4c03-846b-b63d22ebb87d.tar.gz 
INFO[2024-02-27T06:16:33-06:00] Use the results command to check the validation test summary or share the results archive with your Red Hat partner. 
```

**Review by mtulio — COMMENTED** [review]
/lgtm
/approve
/hold

Hey @jcpowermac , thanks for updating. Would you mind to run the `opct report result.tar.gz` command too? (we are missing some presubmits to validate it)

Feel free to drop the `/hold` when the report is validated. :)

Thanks!

**Pull request merged**
