### PR TITLE
SPLAT-868 - plugin: add artifacts collector instance for openshift-tests

### PR DESCRIPTION
**Pull request by mtulio**
Introduce to plugin artifacts collector, to collect:
- e2e suite list for openshift and kubernetes conformance
- must-gather

https://issues.redhat.com/browse/SPLAT-868

Depends:
- https://github.com/redhat-openshift-ecosystem/provider-certification-plugins/pull/23

### CODE REVIEW

**Comment by mtulio** [comment]
@bostrt ptal?

**Comment by mtulio** [comment]
@bostrt rebased and ready for review! ptal? =)

**Comment by bostrt** [comment]
/lgtm

My local test looks great. I will wait until you test completes tomorrow @mtulio but otherwise I'm ready to approval 

```
$ ./openshift-provider-cert-linux-amd64 version
OpenShift Provider Certification Tool: 0.0.0+8418d43
Sonobuoy Version: v0.56.10

$ ./openshift-provider-cert-linux-amd64 status
Tue, 06 Dec 2022 14:58:44 MST> Global Status: complete
JOB_NAME                           | STATUS     | RESULTS    | PROGRESS                  | MESSAGE                                           
10-openshift-kube-conformance      | complete   | failed     | 0/359 (10 failures)       | Total tests processed: 13 (2 pass / 11 failed)    
20-openshift-conformance-validated | complete   | failed     | 0/3454 (10 failures)      | Total tests processed: 13 (2 pass / 11 failed)    
99-openshift-artifacts-collector   | complete   | passed     | 0/0 (0 failures)          | Total tests processed: 3 (3 pass / 0 failed)      
INFO[2022-12-06T14:58:44-07:00] The execution has completed! Use retrieve command to collect the results and share the archive with your Red Hat partner. 

# retrieved and extracted results...

$ ls -la plugins/99-openshift-artifacts-collector/results/global/
total 7508
drwxr-xr-x. 1 rbost rbost     226 Dec  6 14:48 .
drwxr-xr-x. 1 rbost rbost      12 Dec  6 14:48 ..
-rw-r--r--. 1 rbost rbost  815862 Dec  6 14:48 artifacts_e2e-openshift-conformance.txt
-rw-r--r--. 1 rbost rbost   65184 Dec  6 14:48 artifacts_e2e-tests_kubernetes-conformance.txt
-rw-r--r--. 1 rbost rbost 6803076 Dec  6 14:48 artifacts_must-gather.tar.xz
```

**Comment by bostrt** [comment]
/hold 
for marco

**Comment by mtulio** [comment]
Execution finished:

```
$ ./openshift-provider-cert-linux-amd64 version
OpenShift Provider Certification Tool: 0.0.0+7609f71
Sonobuoy Version: v0.56.10

$ ./openshift-provider-cert-linux-amd64 status
Tue, 06 Dec 2022 20:42:43 -03> Global Status: complete
JOB_NAME                           | STATUS     | RESULTS    | PROGRESS                  | MESSAGE                                           
10-openshift-kube-conformance      | complete   | failed     | 352/352 (0 failures)      | Total tests processed: 663 (657 pass / 6 failed)  
20-openshift-conformance-validated | complete   | failed     | 3475/3475 (19 failures)   | Total tests processed: 1747 (1711 pass / 36 failed)
99-openshift-artifacts-collector   | complete   | passed     | 0/0 (0 failures)          | Total tests processed: 3 (3 pass / 0 failed)      
INFO[2022-12-06T20:42:43-03:00] The execution has completed! Use retrieve command to collect the results and share the archive with your Red Hat partner. 


$ ./openshift-provider-cert-linux-amd64 results 202212062041_sonobuoy_2ee00258-38f7-405c-a6d3-caa12b6fbe5d.tar.gz 
Plugin: 10-openshift-kube-conformance
Status: failed
Total: 663
Passed: 657
Failed: 6
Skipped: 0

Plugin: 20-openshift-conformance-validated
Status: failed
Total: 3797
Passed: 1711
Failed: 36
Skipped: 2050

Plugin: 99-openshift-artifacts-collector
Status: passed
Total: 3
Passed: 3
Failed: 0
Skipped: 0
```

**Pull request merged**
